---
title: Literature review distribution models for Psittacidae
author: "JR Ferrer-Paris and AY Sanchez-Mercado"
date: "17/11/2021"
output: html_document
editor_options: 
  chunk_output_type: console
runtime: shiny
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
require(magrittr)
library(dplyr) 
library(tidytext)
library(tidyr)
require(DT)
library(splitstackshape)
options(dplyr.summarise.inform = FALSE)

tables <- c("all_refs","distmodel_ref", "species_ref", "country_ref", "my_bibtex", "birdlife_list", "iso_countries", "Index_of_CITES_Species")
for (tt in tables) {
  if (!exists(tt)) {
    incsv <- sprintf("../input/%s.csv",tt)
    assign(tt,read.csv(incsv,sep=",",header=T, dec=".", stringsAsFactors=F))
  }
}

distmodel_ref %<>% # operador para sobreescribir el objeto con el resultado
  ## quitar corchetes y parentesis
  mutate(across(c(paradigm,model_type,general_application,species_range,species_list,topics,specific_issue,data_source),~gsub("\\{|\\}|\\(|\\)","",.))) %>% 
  ## quitar comillas
  mutate(across(c(general_application,species_list,topics,specific_issue),~gsub("\"","",.,fixed=T))) 

distmodel_ref %<>%
  ## reclasificar categorias de paradigm
  mutate(paradigm_type=case_when(
    paradigm %in% c("RSF,NM","RSF,OM","RSF") ~ "RSF",
    paradigm %in% c("NM") ~ "ENM",
    paradigm %in% c("OM") ~ "OSM",
    is.na(paradigm) ~ as.character(NA),
    TRUE~ "other"
  )) %>%
  ## convertir en factor
  mutate(paradigm_type=factor(paradigm_type,levels=c("ENM","RSF","OSM","other")))

distmodel_ref %>% filter(!is.na(general_application) & !is.na(paradigm) & !(paradigm %in% "none")) %>%
  transmute(topics, general_application,specific_issue,ref_id) -> my.app

## make long with cSplit
long_my.app <-  cSplit(my.app, c("topics", "general_application","specific_issue"), ",", "long")

long_my.app %<>%
  ## reclasificar categorias de topics
  mutate(topics=case_when(
    topics %in% c("evolution") ~ "Evolution",
    general_application %in% c("Threats monitoring","Climate change", "Spatial prediction", "Assessment of distribution","Conservation issues") ~ "Conservation",
    general_application %in% c("Co-occurence of parrot species", "Relation with environmental variables","Macroecology", "Ecological communities") ~ "Ecology",
    general_application %in% c("Temporal distribution patterns","Habitat use related to behaviour types") ~ "Behaviour",
    general_application %in% c("Biogeographic patterns" ) ~ "Evolution",
    general_application %in% c("Predictions of invasion risk","Invasion effect") ~ "Invasion ecology",
    general_application %in% c("Improving estimation") ~ "Methodological issues",
    TRUE ~ topics))

long_my.app %<>% filter(!is.na(topics))
```
# Table of references per topic and general application

First we create a table of topics and general application categories:
```{r}

long_my.app %>%  group_by(topics,general_application,specific_issue) %>% summarise(articles=n()) -> rsm

output$Topics <- DT::renderDataTable({
  rsm %>% datatable
})

DT::DTOutput("Topics")
```

This will show the table of references selected according to the filter above:

```{r}
filteredBibtex <- reactive({
  s = input$Topics_rows_selected
  if (length(s)) {
    ss <- rsm %>% ungroup %>% slice(s)
    filter1 <- ss %>% pull(topics) %>% unique
    filter2 <- ss %>% pull(general_application) %>% unique
    filter3 <- ss %>% pull(sp) %>% unique
     
      slc <- long_my.app %>% filter(topics %in% filter1,general_application %in% filter2 ) %>% pull(ref_id) %>% unique
      my_bibtex %>% filter(UT %in% slc) -> res
  } else {
    my_bibtex -> res
  }
  res
}) 
 
```


```{r}
output$RefList <- DT::renderDataTable({
 
filteredBibtex() %>% 
  transmute(Reference=SR_FULL, Title=TI,
            DOI=if_else(!is.na(DI),sprintf("<a href='http://doi.org/%1$s' target='_blank'>%1$s</a>",DI),
            'no DOI')) %>% 
  datatable(escape=FALSE)
})

DT::DTOutput("RefList")
```

